#!/bin/sh
# 
# Use this script to create a self-signed certificate (ssl.crt) and key file (ssl.key)
# Replace "example.com" with the host name you'd like for your certificate.
# 
openssl genrsa -out ssl.key 2048
openssl req -new -key ssl.key -out ssl.csr -subj "/CN=example.com"
openssl x509 -req -days 365 -in ssl.csr -signkey ssl.key -out ssl.crt




openssl x509 -inform DER -outform PEM -in ssl.crt -out ssl.crt.pem
openssl rsa -inform DER -outform PEM -in ssl.crt -out ssl.crt.pem

cat ssl.crt ssl.key > server.includesprivatekey.pem

https://gist.github.com/stevenhaddox/1501893