// Code generated by protoc-gen-go.
// source: customer.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	customer.proto

It has these top-level messages:
	ExampleRequest
	ExampleResponse
	ExampleFilter
	CreateProductRequest
	CreateCustomerRequest
	CreateSupplierRequest
	StaffRequest
	StaffFilter
	RoleRequest
	ProductRequest
	ProductFilter
	CategoryRequest
	CategoryFilter
	CustomerRequest
	CustomerFilter
	SupplierRequest
	SupplierFilter
	AccountRequest
	AccountFilter
	OrderRequest
	OrderFilter
	PaymentRequest
	PaymentFilter
	OrderDetailRequest
	OrderDetailFilter
	TransactionRequest
	TransactionFilter
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

// Request message for creating a new customer
type ExampleRequest struct {
	Id        uint64                    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name      string                    `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Email     string                    `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Phone     string                    `protobuf:"bytes,4,opt,name=phone" json:"phone,omitempty"`
	Addresses []*ExampleRequest_Address `protobuf:"bytes,5,rep,name=addresses" json:"addresses,omitempty"`
}

func (m *ExampleRequest) Reset()                    { *m = ExampleRequest{} }
func (m *ExampleRequest) String() string            { return proto1.CompactTextString(m) }
func (*ExampleRequest) ProtoMessage()               {}
func (*ExampleRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ExampleRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ExampleRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ExampleRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ExampleRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *ExampleRequest) GetAddresses() []*ExampleRequest_Address {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type ExampleRequest_Address struct {
	Street            string `protobuf:"bytes,1,opt,name=street" json:"street,omitempty"`
	City              string `protobuf:"bytes,2,opt,name=city" json:"city,omitempty"`
	State             string `protobuf:"bytes,3,opt,name=state" json:"state,omitempty"`
	Zip               string `protobuf:"bytes,4,opt,name=zip" json:"zip,omitempty"`
	IsShippingAddress bool   `protobuf:"varint,5,opt,name=isShippingAddress" json:"isShippingAddress,omitempty"`
}

func (m *ExampleRequest_Address) Reset()                    { *m = ExampleRequest_Address{} }
func (m *ExampleRequest_Address) String() string            { return proto1.CompactTextString(m) }
func (*ExampleRequest_Address) ProtoMessage()               {}
func (*ExampleRequest_Address) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *ExampleRequest_Address) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

func (m *ExampleRequest_Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *ExampleRequest_Address) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *ExampleRequest_Address) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

func (m *ExampleRequest_Address) GetIsShippingAddress() bool {
	if m != nil {
		return m.IsShippingAddress
	}
	return false
}

type ExampleResponse struct {
	Id      uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Success bool   `protobuf:"varint,2,opt,name=success" json:"success,omitempty"`
}

func (m *ExampleResponse) Reset()                    { *m = ExampleResponse{} }
func (m *ExampleResponse) String() string            { return proto1.CompactTextString(m) }
func (*ExampleResponse) ProtoMessage()               {}
func (*ExampleResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ExampleResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ExampleResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ExampleFilter struct {
	Keyword string `protobuf:"bytes,1,opt,name=keyword" json:"keyword,omitempty"`
}

func (m *ExampleFilter) Reset()                    { *m = ExampleFilter{} }
func (m *ExampleFilter) String() string            { return proto1.CompactTextString(m) }
func (*ExampleFilter) ProtoMessage()               {}
func (*ExampleFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ExampleFilter) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

type CreateProductRequest struct {
	Product     *ProductRequest     `protobuf:"bytes,1,opt,name=product" json:"product,omitempty"`
	OrderDetail *OrderDetailRequest `protobuf:"bytes,2,opt,name=orderDetail" json:"orderDetail,omitempty"`
}

func (m *CreateProductRequest) Reset()                    { *m = CreateProductRequest{} }
func (m *CreateProductRequest) String() string            { return proto1.CompactTextString(m) }
func (*CreateProductRequest) ProtoMessage()               {}
func (*CreateProductRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CreateProductRequest) GetProduct() *ProductRequest {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *CreateProductRequest) GetOrderDetail() *OrderDetailRequest {
	if m != nil {
		return m.OrderDetail
	}
	return nil
}

type CreateCustomerRequest struct {
	Customer    *CustomerRequest    `protobuf:"bytes,1,opt,name=customer" json:"customer,omitempty"`
	Transaction *TransactionRequest `protobuf:"bytes,2,opt,name=transaction" json:"transaction,omitempty"`
	Account     *AccountRequest     `protobuf:"bytes,3,opt,name=account" json:"account,omitempty"`
}

func (m *CreateCustomerRequest) Reset()                    { *m = CreateCustomerRequest{} }
func (m *CreateCustomerRequest) String() string            { return proto1.CompactTextString(m) }
func (*CreateCustomerRequest) ProtoMessage()               {}
func (*CreateCustomerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CreateCustomerRequest) GetCustomer() *CustomerRequest {
	if m != nil {
		return m.Customer
	}
	return nil
}

func (m *CreateCustomerRequest) GetTransaction() *TransactionRequest {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *CreateCustomerRequest) GetAccount() *AccountRequest {
	if m != nil {
		return m.Account
	}
	return nil
}

type CreateSupplierRequest struct {
	Customer    *SupplierRequest    `protobuf:"bytes,1,opt,name=customer" json:"customer,omitempty"`
	Transaction *TransactionRequest `protobuf:"bytes,2,opt,name=transaction" json:"transaction,omitempty"`
	Account     *AccountRequest     `protobuf:"bytes,3,opt,name=account" json:"account,omitempty"`
}

func (m *CreateSupplierRequest) Reset()                    { *m = CreateSupplierRequest{} }
func (m *CreateSupplierRequest) String() string            { return proto1.CompactTextString(m) }
func (*CreateSupplierRequest) ProtoMessage()               {}
func (*CreateSupplierRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CreateSupplierRequest) GetCustomer() *SupplierRequest {
	if m != nil {
		return m.Customer
	}
	return nil
}

func (m *CreateSupplierRequest) GetTransaction() *TransactionRequest {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *CreateSupplierRequest) GetAccount() *AccountRequest {
	if m != nil {
		return m.Account
	}
	return nil
}

// static objects
type StaffRequest struct {
	StaffId        uint64 `protobuf:"varint,1,opt,name=staffId" json:"staffId,omitempty"`
	RoleId         uint64 `protobuf:"varint,2,opt,name=roleId" json:"roleId,omitempty"`
	StaffImagePath string `protobuf:"bytes,3,opt,name=staffImagePath" json:"staffImagePath,omitempty"`
	FirstName      string `protobuf:"bytes,4,opt,name=firstName" json:"firstName,omitempty"`
	SecondName     string `protobuf:"bytes,5,opt,name=secondName" json:"secondName,omitempty"`
	Email          string `protobuf:"bytes,6,opt,name=email" json:"email,omitempty"`
	Password       string `protobuf:"bytes,7,opt,name=password" json:"password,omitempty"`
	PhoneNumber    string `protobuf:"bytes,8,opt,name=phoneNumber" json:"phoneNumber,omitempty"`
	Address        string `protobuf:"bytes,9,opt,name=address" json:"address,omitempty"`
}

func (m *StaffRequest) Reset()                    { *m = StaffRequest{} }
func (m *StaffRequest) String() string            { return proto1.CompactTextString(m) }
func (*StaffRequest) ProtoMessage()               {}
func (*StaffRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *StaffRequest) GetStaffId() uint64 {
	if m != nil {
		return m.StaffId
	}
	return 0
}

func (m *StaffRequest) GetRoleId() uint64 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *StaffRequest) GetStaffImagePath() string {
	if m != nil {
		return m.StaffImagePath
	}
	return ""
}

func (m *StaffRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *StaffRequest) GetSecondName() string {
	if m != nil {
		return m.SecondName
	}
	return ""
}

func (m *StaffRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *StaffRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *StaffRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *StaffRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type StaffFilter struct {
	StaffKeyword string `protobuf:"bytes,1,opt,name=staffKeyword" json:"staffKeyword,omitempty"`
}

func (m *StaffFilter) Reset()                    { *m = StaffFilter{} }
func (m *StaffFilter) String() string            { return proto1.CompactTextString(m) }
func (*StaffFilter) ProtoMessage()               {}
func (*StaffFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *StaffFilter) GetStaffKeyword() string {
	if m != nil {
		return m.StaffKeyword
	}
	return ""
}

type RoleRequest struct {
	RoleId   uint64 `protobuf:"varint,1,opt,name=roleId" json:"roleId,omitempty"`
	RoleName string `protobuf:"bytes,2,opt,name=roleName" json:"roleName,omitempty"`
}

func (m *RoleRequest) Reset()                    { *m = RoleRequest{} }
func (m *RoleRequest) String() string            { return proto1.CompactTextString(m) }
func (*RoleRequest) ProtoMessage()               {}
func (*RoleRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *RoleRequest) GetRoleId() uint64 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *RoleRequest) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

type ProductRequest struct {
	ProductId        uint64  `protobuf:"varint,1,opt,name=productId" json:"productId,omitempty"`
	ProductImagePath string  `protobuf:"bytes,2,opt,name=productImagePath" json:"productImagePath,omitempty"`
	ProductName      string  `protobuf:"bytes,3,opt,name=productName" json:"productName,omitempty"`
	SupplierId       uint64  `protobuf:"varint,4,opt,name=supplierId" json:"supplierId,omitempty"`
	CategoryId       uint64  `protobuf:"varint,5,opt,name=categoryId" json:"categoryId,omitempty"`
	Barcode          string  `protobuf:"bytes,6,opt,name=barcode" json:"barcode,omitempty"`
	QuantityPerUnit  string  `protobuf:"bytes,7,opt,name=quantityPerUnit" json:"quantityPerUnit,omitempty"`
	SaleUnitPrice    float64 `protobuf:"fixed64,8,opt,name=saleUnitPrice" json:"saleUnitPrice,omitempty"`
	IncomeUnitPrice  float64 `protobuf:"fixed64,9,opt,name=incomeUnitPrice" json:"incomeUnitPrice,omitempty"`
	UnitsInStock     float64 `protobuf:"fixed64,10,opt,name=unitsInStock" json:"unitsInStock,omitempty"`
}

func (m *ProductRequest) Reset()                    { *m = ProductRequest{} }
func (m *ProductRequest) String() string            { return proto1.CompactTextString(m) }
func (*ProductRequest) ProtoMessage()               {}
func (*ProductRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ProductRequest) GetProductId() uint64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *ProductRequest) GetProductImagePath() string {
	if m != nil {
		return m.ProductImagePath
	}
	return ""
}

func (m *ProductRequest) GetProductName() string {
	if m != nil {
		return m.ProductName
	}
	return ""
}

func (m *ProductRequest) GetSupplierId() uint64 {
	if m != nil {
		return m.SupplierId
	}
	return 0
}

func (m *ProductRequest) GetCategoryId() uint64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

func (m *ProductRequest) GetBarcode() string {
	if m != nil {
		return m.Barcode
	}
	return ""
}

func (m *ProductRequest) GetQuantityPerUnit() string {
	if m != nil {
		return m.QuantityPerUnit
	}
	return ""
}

func (m *ProductRequest) GetSaleUnitPrice() float64 {
	if m != nil {
		return m.SaleUnitPrice
	}
	return 0
}

func (m *ProductRequest) GetIncomeUnitPrice() float64 {
	if m != nil {
		return m.IncomeUnitPrice
	}
	return 0
}

func (m *ProductRequest) GetUnitsInStock() float64 {
	if m != nil {
		return m.UnitsInStock
	}
	return 0
}

type ProductFilter struct {
	ProductKeyword string `protobuf:"bytes,1,opt,name=productKeyword" json:"productKeyword,omitempty"`
}

func (m *ProductFilter) Reset()                    { *m = ProductFilter{} }
func (m *ProductFilter) String() string            { return proto1.CompactTextString(m) }
func (*ProductFilter) ProtoMessage()               {}
func (*ProductFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ProductFilter) GetProductKeyword() string {
	if m != nil {
		return m.ProductKeyword
	}
	return ""
}

type CategoryRequest struct {
	CategoryId   uint64 `protobuf:"varint,1,opt,name=categoryId" json:"categoryId,omitempty"`
	CategoryName string `protobuf:"bytes,2,opt,name=categoryName" json:"categoryName,omitempty"`
}

func (m *CategoryRequest) Reset()                    { *m = CategoryRequest{} }
func (m *CategoryRequest) String() string            { return proto1.CompactTextString(m) }
func (*CategoryRequest) ProtoMessage()               {}
func (*CategoryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *CategoryRequest) GetCategoryId() uint64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

func (m *CategoryRequest) GetCategoryName() string {
	if m != nil {
		return m.CategoryName
	}
	return ""
}

type CategoryFilter struct {
	CategoryKeyword string `protobuf:"bytes,1,opt,name=categoryKeyword" json:"categoryKeyword,omitempty"`
}

func (m *CategoryFilter) Reset()                    { *m = CategoryFilter{} }
func (m *CategoryFilter) String() string            { return proto1.CompactTextString(m) }
func (*CategoryFilter) ProtoMessage()               {}
func (*CategoryFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *CategoryFilter) GetCategoryKeyword() string {
	if m != nil {
		return m.CategoryKeyword
	}
	return ""
}

type CustomerRequest struct {
	CustomerId        uint64 `protobuf:"varint,1,opt,name=customerId" json:"customerId,omitempty"`
	CustomerImagePath string `protobuf:"bytes,2,opt,name=customerImagePath" json:"customerImagePath,omitempty"`
	FirstName         string `protobuf:"bytes,3,opt,name=firstName" json:"firstName,omitempty"`
	SecondName        string `protobuf:"bytes,4,opt,name=secondName" json:"secondName,omitempty"`
	PhoneNumber       string `protobuf:"bytes,5,opt,name=phoneNumber" json:"phoneNumber,omitempty"`
	Address           string `protobuf:"bytes,6,opt,name=address" json:"address,omitempty"`
}

func (m *CustomerRequest) Reset()                    { *m = CustomerRequest{} }
func (m *CustomerRequest) String() string            { return proto1.CompactTextString(m) }
func (*CustomerRequest) ProtoMessage()               {}
func (*CustomerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *CustomerRequest) GetCustomerId() uint64 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func (m *CustomerRequest) GetCustomerImagePath() string {
	if m != nil {
		return m.CustomerImagePath
	}
	return ""
}

func (m *CustomerRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *CustomerRequest) GetSecondName() string {
	if m != nil {
		return m.SecondName
	}
	return ""
}

func (m *CustomerRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *CustomerRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type CustomerFilter struct {
	CustomerKeyword string `protobuf:"bytes,1,opt,name=customerKeyword" json:"customerKeyword,omitempty"`
}

func (m *CustomerFilter) Reset()                    { *m = CustomerFilter{} }
func (m *CustomerFilter) String() string            { return proto1.CompactTextString(m) }
func (*CustomerFilter) ProtoMessage()               {}
func (*CustomerFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *CustomerFilter) GetCustomerKeyword() string {
	if m != nil {
		return m.CustomerKeyword
	}
	return ""
}

type SupplierRequest struct {
	SupplierId        uint64 `protobuf:"varint,1,opt,name=supplierId" json:"supplierId,omitempty"`
	SupplierImagePath string `protobuf:"bytes,2,opt,name=supplierImagePath" json:"supplierImagePath,omitempty"`
	CompanyName       string `protobuf:"bytes,3,opt,name=companyName" json:"companyName,omitempty"`
	ContactFname      string `protobuf:"bytes,4,opt,name=contactFname" json:"contactFname,omitempty"`
	PhoneNumber       string `protobuf:"bytes,5,opt,name=phoneNumber" json:"phoneNumber,omitempty"`
	Address           string `protobuf:"bytes,6,opt,name=address" json:"address,omitempty"`
}

func (m *SupplierRequest) Reset()                    { *m = SupplierRequest{} }
func (m *SupplierRequest) String() string            { return proto1.CompactTextString(m) }
func (*SupplierRequest) ProtoMessage()               {}
func (*SupplierRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *SupplierRequest) GetSupplierId() uint64 {
	if m != nil {
		return m.SupplierId
	}
	return 0
}

func (m *SupplierRequest) GetSupplierImagePath() string {
	if m != nil {
		return m.SupplierImagePath
	}
	return ""
}

func (m *SupplierRequest) GetCompanyName() string {
	if m != nil {
		return m.CompanyName
	}
	return ""
}

func (m *SupplierRequest) GetContactFname() string {
	if m != nil {
		return m.ContactFname
	}
	return ""
}

func (m *SupplierRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *SupplierRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type SupplierFilter struct {
	SupplierKeyword string `protobuf:"bytes,1,opt,name=supplierKeyword" json:"supplierKeyword,omitempty"`
}

func (m *SupplierFilter) Reset()                    { *m = SupplierFilter{} }
func (m *SupplierFilter) String() string            { return proto1.CompactTextString(m) }
func (*SupplierFilter) ProtoMessage()               {}
func (*SupplierFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *SupplierFilter) GetSupplierKeyword() string {
	if m != nil {
		return m.SupplierKeyword
	}
	return ""
}

type AccountRequest struct {
	AccountId  uint64  `protobuf:"varint,1,opt,name=accountId" json:"accountId,omitempty"`
	CustomerId uint64  `protobuf:"varint,2,opt,name=customerId" json:"customerId,omitempty"`
	SupplierId uint64  `protobuf:"varint,3,opt,name=supplierId" json:"supplierId,omitempty"`
	Balance    float64 `protobuf:"fixed64,4,opt,name=balance" json:"balance,omitempty"`
}

func (m *AccountRequest) Reset()                    { *m = AccountRequest{} }
func (m *AccountRequest) String() string            { return proto1.CompactTextString(m) }
func (*AccountRequest) ProtoMessage()               {}
func (*AccountRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *AccountRequest) GetAccountId() uint64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *AccountRequest) GetCustomerId() uint64 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func (m *AccountRequest) GetSupplierId() uint64 {
	if m != nil {
		return m.SupplierId
	}
	return 0
}

func (m *AccountRequest) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

type AccountFilter struct {
	AccountKeyword string `protobuf:"bytes,1,opt,name=accountKeyword" json:"accountKeyword,omitempty"`
}

func (m *AccountFilter) Reset()                    { *m = AccountFilter{} }
func (m *AccountFilter) String() string            { return proto1.CompactTextString(m) }
func (*AccountFilter) ProtoMessage()               {}
func (*AccountFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *AccountFilter) GetAccountKeyword() string {
	if m != nil {
		return m.AccountKeyword
	}
	return ""
}

// static objects
type OrderRequest struct {
	OrderId           uint64 `protobuf:"varint,1,opt,name=orderId" json:"orderId,omitempty"`
	OrderDocument     uint32 `protobuf:"varint,2,opt,name=orderDocument" json:"orderDocument,omitempty"`
	MoneyMovementType uint32 `protobuf:"varint,3,opt,name=moneyMovementType" json:"moneyMovementType,omitempty"`
	BillingNo         string `protobuf:"bytes,4,opt,name=billingNo" json:"billingNo,omitempty"`
	StaffId           uint64 `protobuf:"varint,5,opt,name=staffId" json:"staffId,omitempty"`
	CustomerId        uint64 `protobuf:"varint,6,opt,name=customerId" json:"customerId,omitempty"`
	SupplierId        uint64 `protobuf:"varint,7,opt,name=supplierId" json:"supplierId,omitempty"`
	OrderDate         uint64 `protobuf:"varint,8,opt,name=orderDate" json:"orderDate,omitempty"`
	PaymentId         uint64 `protobuf:"varint,9,opt,name=paymentId" json:"paymentId,omitempty"`
	ErrorMsg          string `protobuf:"bytes,10,opt,name=errorMsg" json:"errorMsg,omitempty"`
	Comment           string `protobuf:"bytes,11,opt,name=comment" json:"comment,omitempty"`
	IsDeleted         uint32 `protobuf:"varint,12,opt,name=isDeleted" json:"isDeleted,omitempty"`
	IsPaid            uint32 `protobuf:"varint,13,opt,name=isPaid" json:"isPaid,omitempty"`
	IsEdited          uint32 `protobuf:"varint,14,opt,name=isEdited" json:"isEdited,omitempty"`
}

func (m *OrderRequest) Reset()                    { *m = OrderRequest{} }
func (m *OrderRequest) String() string            { return proto1.CompactTextString(m) }
func (*OrderRequest) ProtoMessage()               {}
func (*OrderRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *OrderRequest) GetOrderId() uint64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *OrderRequest) GetOrderDocument() uint32 {
	if m != nil {
		return m.OrderDocument
	}
	return 0
}

func (m *OrderRequest) GetMoneyMovementType() uint32 {
	if m != nil {
		return m.MoneyMovementType
	}
	return 0
}

func (m *OrderRequest) GetBillingNo() string {
	if m != nil {
		return m.BillingNo
	}
	return ""
}

func (m *OrderRequest) GetStaffId() uint64 {
	if m != nil {
		return m.StaffId
	}
	return 0
}

func (m *OrderRequest) GetCustomerId() uint64 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func (m *OrderRequest) GetSupplierId() uint64 {
	if m != nil {
		return m.SupplierId
	}
	return 0
}

func (m *OrderRequest) GetOrderDate() uint64 {
	if m != nil {
		return m.OrderDate
	}
	return 0
}

func (m *OrderRequest) GetPaymentId() uint64 {
	if m != nil {
		return m.PaymentId
	}
	return 0
}

func (m *OrderRequest) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

func (m *OrderRequest) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *OrderRequest) GetIsDeleted() uint32 {
	if m != nil {
		return m.IsDeleted
	}
	return 0
}

func (m *OrderRequest) GetIsPaid() uint32 {
	if m != nil {
		return m.IsPaid
	}
	return 0
}

func (m *OrderRequest) GetIsEdited() uint32 {
	if m != nil {
		return m.IsEdited
	}
	return 0
}

type OrderFilter struct {
	OrderKeyword string `protobuf:"bytes,1,opt,name=orderKeyword" json:"orderKeyword,omitempty"`
}

func (m *OrderFilter) Reset()                    { *m = OrderFilter{} }
func (m *OrderFilter) String() string            { return proto1.CompactTextString(m) }
func (*OrderFilter) ProtoMessage()               {}
func (*OrderFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *OrderFilter) GetOrderKeyword() string {
	if m != nil {
		return m.OrderKeyword
	}
	return ""
}

type PaymentRequest struct {
	PaymentId              uint64  `protobuf:"varint,1,opt,name=paymentId" json:"paymentId,omitempty"`
	TotalOrderPrice        float64 `protobuf:"fixed64,2,opt,name=totalOrderPrice" json:"totalOrderPrice,omitempty"`
	Discount               float64 `protobuf:"fixed64,3,opt,name=discount" json:"discount,omitempty"`
	TotalPriceWithDiscount float64 `protobuf:"fixed64,4,opt,name=totalPriceWithDiscount" json:"totalPriceWithDiscount,omitempty"`
}

func (m *PaymentRequest) Reset()                    { *m = PaymentRequest{} }
func (m *PaymentRequest) String() string            { return proto1.CompactTextString(m) }
func (*PaymentRequest) ProtoMessage()               {}
func (*PaymentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *PaymentRequest) GetPaymentId() uint64 {
	if m != nil {
		return m.PaymentId
	}
	return 0
}

func (m *PaymentRequest) GetTotalOrderPrice() float64 {
	if m != nil {
		return m.TotalOrderPrice
	}
	return 0
}

func (m *PaymentRequest) GetDiscount() float64 {
	if m != nil {
		return m.Discount
	}
	return 0
}

func (m *PaymentRequest) GetTotalPriceWithDiscount() float64 {
	if m != nil {
		return m.TotalPriceWithDiscount
	}
	return 0
}

type PaymentFilter struct {
	PaymentKeyword string `protobuf:"bytes,1,opt,name=paymentKeyword" json:"paymentKeyword,omitempty"`
}

func (m *PaymentFilter) Reset()                    { *m = PaymentFilter{} }
func (m *PaymentFilter) String() string            { return proto1.CompactTextString(m) }
func (*PaymentFilter) ProtoMessage()               {}
func (*PaymentFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *PaymentFilter) GetPaymentKeyword() string {
	if m != nil {
		return m.PaymentKeyword
	}
	return ""
}

type OrderDetailRequest struct {
	OrderDetailId uint64  `protobuf:"varint,1,opt,name=orderDetailId" json:"orderDetailId,omitempty"`
	OrderId       uint64  `protobuf:"varint,2,opt,name=orderId" json:"orderId,omitempty"`
	ProductId     uint64  `protobuf:"varint,3,opt,name=productId" json:"productId,omitempty"`
	BillingNo     string  `protobuf:"bytes,4,opt,name=billingNo" json:"billingNo,omitempty"`
	Price         float64 `protobuf:"fixed64,5,opt,name=price" json:"price,omitempty"`
	OrderQuantity float64 `protobuf:"fixed64,6,opt,name=orderQuantity" json:"orderQuantity,omitempty"`
	Discount      int32   `protobuf:"varint,7,opt,name=discount" json:"discount,omitempty"`
}

func (m *OrderDetailRequest) Reset()                    { *m = OrderDetailRequest{} }
func (m *OrderDetailRequest) String() string            { return proto1.CompactTextString(m) }
func (*OrderDetailRequest) ProtoMessage()               {}
func (*OrderDetailRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *OrderDetailRequest) GetOrderDetailId() uint64 {
	if m != nil {
		return m.OrderDetailId
	}
	return 0
}

func (m *OrderDetailRequest) GetOrderId() uint64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *OrderDetailRequest) GetProductId() uint64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *OrderDetailRequest) GetBillingNo() string {
	if m != nil {
		return m.BillingNo
	}
	return ""
}

func (m *OrderDetailRequest) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *OrderDetailRequest) GetOrderQuantity() float64 {
	if m != nil {
		return m.OrderQuantity
	}
	return 0
}

func (m *OrderDetailRequest) GetDiscount() int32 {
	if m != nil {
		return m.Discount
	}
	return 0
}

type OrderDetailFilter struct {
	OrderDetailKeyword string `protobuf:"bytes,1,opt,name=orderDetailKeyword" json:"orderDetailKeyword,omitempty"`
}

func (m *OrderDetailFilter) Reset()                    { *m = OrderDetailFilter{} }
func (m *OrderDetailFilter) String() string            { return proto1.CompactTextString(m) }
func (*OrderDetailFilter) ProtoMessage()               {}
func (*OrderDetailFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *OrderDetailFilter) GetOrderDetailKeyword() string {
	if m != nil {
		return m.OrderDetailKeyword
	}
	return ""
}

type TransactionRequest struct {
	TransactionId   uint64  `protobuf:"varint,1,opt,name=transactionId" json:"transactionId,omitempty"`
	TransactionDate uint64  `protobuf:"varint,2,opt,name=transactionDate" json:"transactionDate,omitempty"`
	TransactionType uint32  `protobuf:"varint,3,opt,name=transactionType" json:"transactionType,omitempty"`
	MoneyAmount     float64 `protobuf:"fixed64,4,opt,name=moneyAmount" json:"moneyAmount,omitempty"`
	OrderId         uint64  `protobuf:"varint,5,opt,name=orderId" json:"orderId,omitempty"`
	CustomerId      uint64  `protobuf:"varint,6,opt,name=customerId" json:"customerId,omitempty"`
	SupplierId      uint64  `protobuf:"varint,7,opt,name=supplierId" json:"supplierId,omitempty"`
	StaffId         uint64  `protobuf:"varint,8,opt,name=staffId" json:"staffId,omitempty"`
}

func (m *TransactionRequest) Reset()                    { *m = TransactionRequest{} }
func (m *TransactionRequest) String() string            { return proto1.CompactTextString(m) }
func (*TransactionRequest) ProtoMessage()               {}
func (*TransactionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *TransactionRequest) GetTransactionId() uint64 {
	if m != nil {
		return m.TransactionId
	}
	return 0
}

func (m *TransactionRequest) GetTransactionDate() uint64 {
	if m != nil {
		return m.TransactionDate
	}
	return 0
}

func (m *TransactionRequest) GetTransactionType() uint32 {
	if m != nil {
		return m.TransactionType
	}
	return 0
}

func (m *TransactionRequest) GetMoneyAmount() float64 {
	if m != nil {
		return m.MoneyAmount
	}
	return 0
}

func (m *TransactionRequest) GetOrderId() uint64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *TransactionRequest) GetCustomerId() uint64 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func (m *TransactionRequest) GetSupplierId() uint64 {
	if m != nil {
		return m.SupplierId
	}
	return 0
}

func (m *TransactionRequest) GetStaffId() uint64 {
	if m != nil {
		return m.StaffId
	}
	return 0
}

type TransactionFilter struct {
	TransactionKeyword string `protobuf:"bytes,1,opt,name=transactionKeyword" json:"transactionKeyword,omitempty"`
}

func (m *TransactionFilter) Reset()                    { *m = TransactionFilter{} }
func (m *TransactionFilter) String() string            { return proto1.CompactTextString(m) }
func (*TransactionFilter) ProtoMessage()               {}
func (*TransactionFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *TransactionFilter) GetTransactionKeyword() string {
	if m != nil {
		return m.TransactionKeyword
	}
	return ""
}

func init() {
	proto1.RegisterType((*ExampleRequest)(nil), "proto.ExampleRequest")
	proto1.RegisterType((*ExampleRequest_Address)(nil), "proto.ExampleRequest.Address")
	proto1.RegisterType((*ExampleResponse)(nil), "proto.ExampleResponse")
	proto1.RegisterType((*ExampleFilter)(nil), "proto.ExampleFilter")
	proto1.RegisterType((*CreateProductRequest)(nil), "proto.CreateProductRequest")
	proto1.RegisterType((*CreateCustomerRequest)(nil), "proto.CreateCustomerRequest")
	proto1.RegisterType((*CreateSupplierRequest)(nil), "proto.CreateSupplierRequest")
	proto1.RegisterType((*StaffRequest)(nil), "proto.StaffRequest")
	proto1.RegisterType((*StaffFilter)(nil), "proto.StaffFilter")
	proto1.RegisterType((*RoleRequest)(nil), "proto.RoleRequest")
	proto1.RegisterType((*ProductRequest)(nil), "proto.ProductRequest")
	proto1.RegisterType((*ProductFilter)(nil), "proto.ProductFilter")
	proto1.RegisterType((*CategoryRequest)(nil), "proto.CategoryRequest")
	proto1.RegisterType((*CategoryFilter)(nil), "proto.CategoryFilter")
	proto1.RegisterType((*CustomerRequest)(nil), "proto.CustomerRequest")
	proto1.RegisterType((*CustomerFilter)(nil), "proto.CustomerFilter")
	proto1.RegisterType((*SupplierRequest)(nil), "proto.SupplierRequest")
	proto1.RegisterType((*SupplierFilter)(nil), "proto.SupplierFilter")
	proto1.RegisterType((*AccountRequest)(nil), "proto.AccountRequest")
	proto1.RegisterType((*AccountFilter)(nil), "proto.AccountFilter")
	proto1.RegisterType((*OrderRequest)(nil), "proto.OrderRequest")
	proto1.RegisterType((*OrderFilter)(nil), "proto.OrderFilter")
	proto1.RegisterType((*PaymentRequest)(nil), "proto.PaymentRequest")
	proto1.RegisterType((*PaymentFilter)(nil), "proto.PaymentFilter")
	proto1.RegisterType((*OrderDetailRequest)(nil), "proto.OrderDetailRequest")
	proto1.RegisterType((*OrderDetailFilter)(nil), "proto.OrderDetailFilter")
	proto1.RegisterType((*TransactionRequest)(nil), "proto.TransactionRequest")
	proto1.RegisterType((*TransactionFilter)(nil), "proto.TransactionFilter")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RentautomationService service

type RentautomationServiceClient interface {
	GetExamples(ctx context.Context, in *ExampleFilter, opts ...grpc.CallOption) (RentautomationService_GetExamplesClient, error)
	CreateExample(ctx context.Context, in *ExampleRequest, opts ...grpc.CallOption) (*ExampleResponse, error)
	CreateAccount(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*AccountRequest, error)
	GetAccounts(ctx context.Context, in *AccountFilter, opts ...grpc.CallOption) (RentautomationService_GetAccountsClient, error)
	CreateCategory(ctx context.Context, in *CategoryRequest, opts ...grpc.CallOption) (*CategoryRequest, error)
	GetCategories(ctx context.Context, in *CategoryFilter, opts ...grpc.CallOption) (RentautomationService_GetCategoriesClient, error)
	CreateCustomer(ctx context.Context, in *CustomerRequest, opts ...grpc.CallOption) (*CustomerRequest, error)
	GetCustomers(ctx context.Context, in *CustomerFilter, opts ...grpc.CallOption) (RentautomationService_GetCustomersClient, error)
	CreateOrder(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderRequest, error)
	GetOrders(ctx context.Context, in *OrderFilter, opts ...grpc.CallOption) (RentautomationService_GetOrdersClient, error)
	CreateOrderDetail(ctx context.Context, in *OrderDetailRequest, opts ...grpc.CallOption) (*OrderDetailRequest, error)
	GetOrderDetails(ctx context.Context, in *OrderDetailFilter, opts ...grpc.CallOption) (RentautomationService_GetOrderDetailsClient, error)
	CreatePayment(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*PaymentRequest, error)
	GetPayments(ctx context.Context, in *PaymentFilter, opts ...grpc.CallOption) (RentautomationService_GetPaymentsClient, error)
	CreateProduct(ctx context.Context, in *ProductRequest, opts ...grpc.CallOption) (*ProductRequest, error)
	GetProducts(ctx context.Context, in *ProductFilter, opts ...grpc.CallOption) (RentautomationService_GetProductsClient, error)
	CreateStaff(ctx context.Context, in *StaffRequest, opts ...grpc.CallOption) (*StaffRequest, error)
	GetStaff(ctx context.Context, in *StaffFilter, opts ...grpc.CallOption) (RentautomationService_GetStaffClient, error)
	CreateTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionRequest, error)
	GetTransactions(ctx context.Context, in *TransactionFilter, opts ...grpc.CallOption) (RentautomationService_GetTransactionsClient, error)
	// ------------------ New methods ------------------ //
	CreateProductWith(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductRequest, error)
	UpdateProductWith(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductRequest, error)
	CreateCustomerWith(ctx context.Context, in *CreateCustomerRequest, opts ...grpc.CallOption) (*CreateCustomerRequest, error)
	UpdateCustomerWith(ctx context.Context, in *CustomerRequest, opts ...grpc.CallOption) (*CustomerRequest, error)
	UpdateCustomerBalanceWith(ctx context.Context, in *CreateCustomerRequest, opts ...grpc.CallOption) (*CreateCustomerRequest, error)
	CreateSupplierWith(ctx context.Context, in *CreateSupplierRequest, opts ...grpc.CallOption) (*CreateSupplierRequest, error)
	UpdateSupplierWith(ctx context.Context, in *SupplierRequest, opts ...grpc.CallOption) (*SupplierRequest, error)
	UpdateSupplierBalanceWith(ctx context.Context, in *CreateSupplierRequest, opts ...grpc.CallOption) (*CreateSupplierRequest, error)
	CreateStaffWith(ctx context.Context, in *StaffRequest, opts ...grpc.CallOption) (*StaffRequest, error)
	UpdateStaffWith(ctx context.Context, in *StaffRequest, opts ...grpc.CallOption) (*StaffRequest, error)
}

type rentautomationServiceClient struct {
	cc *grpc.ClientConn
}

func NewRentautomationServiceClient(cc *grpc.ClientConn) RentautomationServiceClient {
	return &rentautomationServiceClient{cc}
}

func (c *rentautomationServiceClient) GetExamples(ctx context.Context, in *ExampleFilter, opts ...grpc.CallOption) (RentautomationService_GetExamplesClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_RentautomationService_serviceDesc.Streams[0], c.cc, "/proto.RentautomationService/GetExamples", opts...)
	if err != nil {
		return nil, err
	}
	x := &rentautomationServiceGetExamplesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RentautomationService_GetExamplesClient interface {
	Recv() (*ExampleRequest, error)
	grpc.ClientStream
}

type rentautomationServiceGetExamplesClient struct {
	grpc.ClientStream
}

func (x *rentautomationServiceGetExamplesClient) Recv() (*ExampleRequest, error) {
	m := new(ExampleRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *rentautomationServiceClient) CreateExample(ctx context.Context, in *ExampleRequest, opts ...grpc.CallOption) (*ExampleResponse, error) {
	out := new(ExampleResponse)
	err := grpc.Invoke(ctx, "/proto.RentautomationService/CreateExample", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rentautomationServiceClient) CreateAccount(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*AccountRequest, error) {
	out := new(AccountRequest)
	err := grpc.Invoke(ctx, "/proto.RentautomationService/CreateAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rentautomationServiceClient) GetAccounts(ctx context.Context, in *AccountFilter, opts ...grpc.CallOption) (RentautomationService_GetAccountsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_RentautomationService_serviceDesc.Streams[1], c.cc, "/proto.RentautomationService/GetAccounts", opts...)
	if err != nil {
		return nil, err
	}
	x := &rentautomationServiceGetAccountsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RentautomationService_GetAccountsClient interface {
	Recv() (*AccountRequest, error)
	grpc.ClientStream
}

type rentautomationServiceGetAccountsClient struct {
	grpc.ClientStream
}

func (x *rentautomationServiceGetAccountsClient) Recv() (*AccountRequest, error) {
	m := new(AccountRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *rentautomationServiceClient) CreateCategory(ctx context.Context, in *CategoryRequest, opts ...grpc.CallOption) (*CategoryRequest, error) {
	out := new(CategoryRequest)
	err := grpc.Invoke(ctx, "/proto.RentautomationService/CreateCategory", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rentautomationServiceClient) GetCategories(ctx context.Context, in *CategoryFilter, opts ...grpc.CallOption) (RentautomationService_GetCategoriesClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_RentautomationService_serviceDesc.Streams[2], c.cc, "/proto.RentautomationService/GetCategories", opts...)
	if err != nil {
		return nil, err
	}
	x := &rentautomationServiceGetCategoriesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RentautomationService_GetCategoriesClient interface {
	Recv() (*CategoryRequest, error)
	grpc.ClientStream
}

type rentautomationServiceGetCategoriesClient struct {
	grpc.ClientStream
}

func (x *rentautomationServiceGetCategoriesClient) Recv() (*CategoryRequest, error) {
	m := new(CategoryRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *rentautomationServiceClient) CreateCustomer(ctx context.Context, in *CustomerRequest, opts ...grpc.CallOption) (*CustomerRequest, error) {
	out := new(CustomerRequest)
	err := grpc.Invoke(ctx, "/proto.RentautomationService/CreateCustomer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rentautomationServiceClient) GetCustomers(ctx context.Context, in *CustomerFilter, opts ...grpc.CallOption) (RentautomationService_GetCustomersClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_RentautomationService_serviceDesc.Streams[3], c.cc, "/proto.RentautomationService/GetCustomers", opts...)
	if err != nil {
		return nil, err
	}
	x := &rentautomationServiceGetCustomersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RentautomationService_GetCustomersClient interface {
	Recv() (*CustomerRequest, error)
	grpc.ClientStream
}

type rentautomationServiceGetCustomersClient struct {
	grpc.ClientStream
}

func (x *rentautomationServiceGetCustomersClient) Recv() (*CustomerRequest, error) {
	m := new(CustomerRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *rentautomationServiceClient) CreateOrder(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderRequest, error) {
	out := new(OrderRequest)
	err := grpc.Invoke(ctx, "/proto.RentautomationService/CreateOrder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rentautomationServiceClient) GetOrders(ctx context.Context, in *OrderFilter, opts ...grpc.CallOption) (RentautomationService_GetOrdersClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_RentautomationService_serviceDesc.Streams[4], c.cc, "/proto.RentautomationService/GetOrders", opts...)
	if err != nil {
		return nil, err
	}
	x := &rentautomationServiceGetOrdersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RentautomationService_GetOrdersClient interface {
	Recv() (*OrderRequest, error)
	grpc.ClientStream
}

type rentautomationServiceGetOrdersClient struct {
	grpc.ClientStream
}

func (x *rentautomationServiceGetOrdersClient) Recv() (*OrderRequest, error) {
	m := new(OrderRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *rentautomationServiceClient) CreateOrderDetail(ctx context.Context, in *OrderDetailRequest, opts ...grpc.CallOption) (*OrderDetailRequest, error) {
	out := new(OrderDetailRequest)
	err := grpc.Invoke(ctx, "/proto.RentautomationService/CreateOrderDetail", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rentautomationServiceClient) GetOrderDetails(ctx context.Context, in *OrderDetailFilter, opts ...grpc.CallOption) (RentautomationService_GetOrderDetailsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_RentautomationService_serviceDesc.Streams[5], c.cc, "/proto.RentautomationService/GetOrderDetails", opts...)
	if err != nil {
		return nil, err
	}
	x := &rentautomationServiceGetOrderDetailsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RentautomationService_GetOrderDetailsClient interface {
	Recv() (*OrderDetailRequest, error)
	grpc.ClientStream
}

type rentautomationServiceGetOrderDetailsClient struct {
	grpc.ClientStream
}

func (x *rentautomationServiceGetOrderDetailsClient) Recv() (*OrderDetailRequest, error) {
	m := new(OrderDetailRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *rentautomationServiceClient) CreatePayment(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*PaymentRequest, error) {
	out := new(PaymentRequest)
	err := grpc.Invoke(ctx, "/proto.RentautomationService/CreatePayment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rentautomationServiceClient) GetPayments(ctx context.Context, in *PaymentFilter, opts ...grpc.CallOption) (RentautomationService_GetPaymentsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_RentautomationService_serviceDesc.Streams[6], c.cc, "/proto.RentautomationService/GetPayments", opts...)
	if err != nil {
		return nil, err
	}
	x := &rentautomationServiceGetPaymentsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RentautomationService_GetPaymentsClient interface {
	Recv() (*PaymentRequest, error)
	grpc.ClientStream
}

type rentautomationServiceGetPaymentsClient struct {
	grpc.ClientStream
}

func (x *rentautomationServiceGetPaymentsClient) Recv() (*PaymentRequest, error) {
	m := new(PaymentRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *rentautomationServiceClient) CreateProduct(ctx context.Context, in *ProductRequest, opts ...grpc.CallOption) (*ProductRequest, error) {
	out := new(ProductRequest)
	err := grpc.Invoke(ctx, "/proto.RentautomationService/CreateProduct", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rentautomationServiceClient) GetProducts(ctx context.Context, in *ProductFilter, opts ...grpc.CallOption) (RentautomationService_GetProductsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_RentautomationService_serviceDesc.Streams[7], c.cc, "/proto.RentautomationService/GetProducts", opts...)
	if err != nil {
		return nil, err
	}
	x := &rentautomationServiceGetProductsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RentautomationService_GetProductsClient interface {
	Recv() (*ProductRequest, error)
	grpc.ClientStream
}

type rentautomationServiceGetProductsClient struct {
	grpc.ClientStream
}

func (x *rentautomationServiceGetProductsClient) Recv() (*ProductRequest, error) {
	m := new(ProductRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *rentautomationServiceClient) CreateStaff(ctx context.Context, in *StaffRequest, opts ...grpc.CallOption) (*StaffRequest, error) {
	out := new(StaffRequest)
	err := grpc.Invoke(ctx, "/proto.RentautomationService/CreateStaff", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rentautomationServiceClient) GetStaff(ctx context.Context, in *StaffFilter, opts ...grpc.CallOption) (RentautomationService_GetStaffClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_RentautomationService_serviceDesc.Streams[8], c.cc, "/proto.RentautomationService/GetStaff", opts...)
	if err != nil {
		return nil, err
	}
	x := &rentautomationServiceGetStaffClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RentautomationService_GetStaffClient interface {
	Recv() (*StaffRequest, error)
	grpc.ClientStream
}

type rentautomationServiceGetStaffClient struct {
	grpc.ClientStream
}

func (x *rentautomationServiceGetStaffClient) Recv() (*StaffRequest, error) {
	m := new(StaffRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *rentautomationServiceClient) CreateTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionRequest, error) {
	out := new(TransactionRequest)
	err := grpc.Invoke(ctx, "/proto.RentautomationService/CreateTransaction", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rentautomationServiceClient) GetTransactions(ctx context.Context, in *TransactionFilter, opts ...grpc.CallOption) (RentautomationService_GetTransactionsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_RentautomationService_serviceDesc.Streams[9], c.cc, "/proto.RentautomationService/GetTransactions", opts...)
	if err != nil {
		return nil, err
	}
	x := &rentautomationServiceGetTransactionsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RentautomationService_GetTransactionsClient interface {
	Recv() (*TransactionRequest, error)
	grpc.ClientStream
}

type rentautomationServiceGetTransactionsClient struct {
	grpc.ClientStream
}

func (x *rentautomationServiceGetTransactionsClient) Recv() (*TransactionRequest, error) {
	m := new(TransactionRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *rentautomationServiceClient) CreateProductWith(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductRequest, error) {
	out := new(CreateProductRequest)
	err := grpc.Invoke(ctx, "/proto.RentautomationService/CreateProductWith", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rentautomationServiceClient) UpdateProductWith(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductRequest, error) {
	out := new(CreateProductRequest)
	err := grpc.Invoke(ctx, "/proto.RentautomationService/UpdateProductWith", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rentautomationServiceClient) CreateCustomerWith(ctx context.Context, in *CreateCustomerRequest, opts ...grpc.CallOption) (*CreateCustomerRequest, error) {
	out := new(CreateCustomerRequest)
	err := grpc.Invoke(ctx, "/proto.RentautomationService/CreateCustomerWith", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rentautomationServiceClient) UpdateCustomerWith(ctx context.Context, in *CustomerRequest, opts ...grpc.CallOption) (*CustomerRequest, error) {
	out := new(CustomerRequest)
	err := grpc.Invoke(ctx, "/proto.RentautomationService/UpdateCustomerWith", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rentautomationServiceClient) UpdateCustomerBalanceWith(ctx context.Context, in *CreateCustomerRequest, opts ...grpc.CallOption) (*CreateCustomerRequest, error) {
	out := new(CreateCustomerRequest)
	err := grpc.Invoke(ctx, "/proto.RentautomationService/UpdateCustomerBalanceWith", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rentautomationServiceClient) CreateSupplierWith(ctx context.Context, in *CreateSupplierRequest, opts ...grpc.CallOption) (*CreateSupplierRequest, error) {
	out := new(CreateSupplierRequest)
	err := grpc.Invoke(ctx, "/proto.RentautomationService/CreateSupplierWith", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rentautomationServiceClient) UpdateSupplierWith(ctx context.Context, in *SupplierRequest, opts ...grpc.CallOption) (*SupplierRequest, error) {
	out := new(SupplierRequest)
	err := grpc.Invoke(ctx, "/proto.RentautomationService/UpdateSupplierWith", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rentautomationServiceClient) UpdateSupplierBalanceWith(ctx context.Context, in *CreateSupplierRequest, opts ...grpc.CallOption) (*CreateSupplierRequest, error) {
	out := new(CreateSupplierRequest)
	err := grpc.Invoke(ctx, "/proto.RentautomationService/UpdateSupplierBalanceWith", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rentautomationServiceClient) CreateStaffWith(ctx context.Context, in *StaffRequest, opts ...grpc.CallOption) (*StaffRequest, error) {
	out := new(StaffRequest)
	err := grpc.Invoke(ctx, "/proto.RentautomationService/CreateStaffWith", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rentautomationServiceClient) UpdateStaffWith(ctx context.Context, in *StaffRequest, opts ...grpc.CallOption) (*StaffRequest, error) {
	out := new(StaffRequest)
	err := grpc.Invoke(ctx, "/proto.RentautomationService/UpdateStaffWith", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RentautomationService service

type RentautomationServiceServer interface {
	GetExamples(*ExampleFilter, RentautomationService_GetExamplesServer) error
	CreateExample(context.Context, *ExampleRequest) (*ExampleResponse, error)
	CreateAccount(context.Context, *AccountRequest) (*AccountRequest, error)
	GetAccounts(*AccountFilter, RentautomationService_GetAccountsServer) error
	CreateCategory(context.Context, *CategoryRequest) (*CategoryRequest, error)
	GetCategories(*CategoryFilter, RentautomationService_GetCategoriesServer) error
	CreateCustomer(context.Context, *CustomerRequest) (*CustomerRequest, error)
	GetCustomers(*CustomerFilter, RentautomationService_GetCustomersServer) error
	CreateOrder(context.Context, *OrderRequest) (*OrderRequest, error)
	GetOrders(*OrderFilter, RentautomationService_GetOrdersServer) error
	CreateOrderDetail(context.Context, *OrderDetailRequest) (*OrderDetailRequest, error)
	GetOrderDetails(*OrderDetailFilter, RentautomationService_GetOrderDetailsServer) error
	CreatePayment(context.Context, *PaymentRequest) (*PaymentRequest, error)
	GetPayments(*PaymentFilter, RentautomationService_GetPaymentsServer) error
	CreateProduct(context.Context, *ProductRequest) (*ProductRequest, error)
	GetProducts(*ProductFilter, RentautomationService_GetProductsServer) error
	CreateStaff(context.Context, *StaffRequest) (*StaffRequest, error)
	GetStaff(*StaffFilter, RentautomationService_GetStaffServer) error
	CreateTransaction(context.Context, *TransactionRequest) (*TransactionRequest, error)
	GetTransactions(*TransactionFilter, RentautomationService_GetTransactionsServer) error
	// ------------------ New methods ------------------ //
	CreateProductWith(context.Context, *CreateProductRequest) (*CreateProductRequest, error)
	UpdateProductWith(context.Context, *CreateProductRequest) (*CreateProductRequest, error)
	CreateCustomerWith(context.Context, *CreateCustomerRequest) (*CreateCustomerRequest, error)
	UpdateCustomerWith(context.Context, *CustomerRequest) (*CustomerRequest, error)
	UpdateCustomerBalanceWith(context.Context, *CreateCustomerRequest) (*CreateCustomerRequest, error)
	CreateSupplierWith(context.Context, *CreateSupplierRequest) (*CreateSupplierRequest, error)
	UpdateSupplierWith(context.Context, *SupplierRequest) (*SupplierRequest, error)
	UpdateSupplierBalanceWith(context.Context, *CreateSupplierRequest) (*CreateSupplierRequest, error)
	CreateStaffWith(context.Context, *StaffRequest) (*StaffRequest, error)
	UpdateStaffWith(context.Context, *StaffRequest) (*StaffRequest, error)
}

func RegisterRentautomationServiceServer(s *grpc.Server, srv RentautomationServiceServer) {
	s.RegisterService(&_RentautomationService_serviceDesc, srv)
}

func _RentautomationService_GetExamples_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExampleFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RentautomationServiceServer).GetExamples(m, &rentautomationServiceGetExamplesServer{stream})
}

type RentautomationService_GetExamplesServer interface {
	Send(*ExampleRequest) error
	grpc.ServerStream
}

type rentautomationServiceGetExamplesServer struct {
	grpc.ServerStream
}

func (x *rentautomationServiceGetExamplesServer) Send(m *ExampleRequest) error {
	return x.ServerStream.SendMsg(m)
}

func _RentautomationService_CreateExample_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExampleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RentautomationServiceServer).CreateExample(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RentautomationService/CreateExample",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RentautomationServiceServer).CreateExample(ctx, req.(*ExampleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RentautomationService_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RentautomationServiceServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RentautomationService/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RentautomationServiceServer).CreateAccount(ctx, req.(*AccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RentautomationService_GetAccounts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AccountFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RentautomationServiceServer).GetAccounts(m, &rentautomationServiceGetAccountsServer{stream})
}

type RentautomationService_GetAccountsServer interface {
	Send(*AccountRequest) error
	grpc.ServerStream
}

type rentautomationServiceGetAccountsServer struct {
	grpc.ServerStream
}

func (x *rentautomationServiceGetAccountsServer) Send(m *AccountRequest) error {
	return x.ServerStream.SendMsg(m)
}

func _RentautomationService_CreateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RentautomationServiceServer).CreateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RentautomationService/CreateCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RentautomationServiceServer).CreateCategory(ctx, req.(*CategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RentautomationService_GetCategories_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CategoryFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RentautomationServiceServer).GetCategories(m, &rentautomationServiceGetCategoriesServer{stream})
}

type RentautomationService_GetCategoriesServer interface {
	Send(*CategoryRequest) error
	grpc.ServerStream
}

type rentautomationServiceGetCategoriesServer struct {
	grpc.ServerStream
}

func (x *rentautomationServiceGetCategoriesServer) Send(m *CategoryRequest) error {
	return x.ServerStream.SendMsg(m)
}

func _RentautomationService_CreateCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RentautomationServiceServer).CreateCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RentautomationService/CreateCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RentautomationServiceServer).CreateCustomer(ctx, req.(*CustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RentautomationService_GetCustomers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CustomerFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RentautomationServiceServer).GetCustomers(m, &rentautomationServiceGetCustomersServer{stream})
}

type RentautomationService_GetCustomersServer interface {
	Send(*CustomerRequest) error
	grpc.ServerStream
}

type rentautomationServiceGetCustomersServer struct {
	grpc.ServerStream
}

func (x *rentautomationServiceGetCustomersServer) Send(m *CustomerRequest) error {
	return x.ServerStream.SendMsg(m)
}

func _RentautomationService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RentautomationServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RentautomationService/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RentautomationServiceServer).CreateOrder(ctx, req.(*OrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RentautomationService_GetOrders_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OrderFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RentautomationServiceServer).GetOrders(m, &rentautomationServiceGetOrdersServer{stream})
}

type RentautomationService_GetOrdersServer interface {
	Send(*OrderRequest) error
	grpc.ServerStream
}

type rentautomationServiceGetOrdersServer struct {
	grpc.ServerStream
}

func (x *rentautomationServiceGetOrdersServer) Send(m *OrderRequest) error {
	return x.ServerStream.SendMsg(m)
}

func _RentautomationService_CreateOrderDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RentautomationServiceServer).CreateOrderDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RentautomationService/CreateOrderDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RentautomationServiceServer).CreateOrderDetail(ctx, req.(*OrderDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RentautomationService_GetOrderDetails_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OrderDetailFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RentautomationServiceServer).GetOrderDetails(m, &rentautomationServiceGetOrderDetailsServer{stream})
}

type RentautomationService_GetOrderDetailsServer interface {
	Send(*OrderDetailRequest) error
	grpc.ServerStream
}

type rentautomationServiceGetOrderDetailsServer struct {
	grpc.ServerStream
}

func (x *rentautomationServiceGetOrderDetailsServer) Send(m *OrderDetailRequest) error {
	return x.ServerStream.SendMsg(m)
}

func _RentautomationService_CreatePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RentautomationServiceServer).CreatePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RentautomationService/CreatePayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RentautomationServiceServer).CreatePayment(ctx, req.(*PaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RentautomationService_GetPayments_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PaymentFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RentautomationServiceServer).GetPayments(m, &rentautomationServiceGetPaymentsServer{stream})
}

type RentautomationService_GetPaymentsServer interface {
	Send(*PaymentRequest) error
	grpc.ServerStream
}

type rentautomationServiceGetPaymentsServer struct {
	grpc.ServerStream
}

func (x *rentautomationServiceGetPaymentsServer) Send(m *PaymentRequest) error {
	return x.ServerStream.SendMsg(m)
}

func _RentautomationService_CreateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RentautomationServiceServer).CreateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RentautomationService/CreateProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RentautomationServiceServer).CreateProduct(ctx, req.(*ProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RentautomationService_GetProducts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProductFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RentautomationServiceServer).GetProducts(m, &rentautomationServiceGetProductsServer{stream})
}

type RentautomationService_GetProductsServer interface {
	Send(*ProductRequest) error
	grpc.ServerStream
}

type rentautomationServiceGetProductsServer struct {
	grpc.ServerStream
}

func (x *rentautomationServiceGetProductsServer) Send(m *ProductRequest) error {
	return x.ServerStream.SendMsg(m)
}

func _RentautomationService_CreateStaff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RentautomationServiceServer).CreateStaff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RentautomationService/CreateStaff",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RentautomationServiceServer).CreateStaff(ctx, req.(*StaffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RentautomationService_GetStaff_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StaffFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RentautomationServiceServer).GetStaff(m, &rentautomationServiceGetStaffServer{stream})
}

type RentautomationService_GetStaffServer interface {
	Send(*StaffRequest) error
	grpc.ServerStream
}

type rentautomationServiceGetStaffServer struct {
	grpc.ServerStream
}

func (x *rentautomationServiceGetStaffServer) Send(m *StaffRequest) error {
	return x.ServerStream.SendMsg(m)
}

func _RentautomationService_CreateTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RentautomationServiceServer).CreateTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RentautomationService/CreateTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RentautomationServiceServer).CreateTransaction(ctx, req.(*TransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RentautomationService_GetTransactions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TransactionFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RentautomationServiceServer).GetTransactions(m, &rentautomationServiceGetTransactionsServer{stream})
}

type RentautomationService_GetTransactionsServer interface {
	Send(*TransactionRequest) error
	grpc.ServerStream
}

type rentautomationServiceGetTransactionsServer struct {
	grpc.ServerStream
}

func (x *rentautomationServiceGetTransactionsServer) Send(m *TransactionRequest) error {
	return x.ServerStream.SendMsg(m)
}

func _RentautomationService_CreateProductWith_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RentautomationServiceServer).CreateProductWith(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RentautomationService/CreateProductWith",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RentautomationServiceServer).CreateProductWith(ctx, req.(*CreateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RentautomationService_UpdateProductWith_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RentautomationServiceServer).UpdateProductWith(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RentautomationService/UpdateProductWith",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RentautomationServiceServer).UpdateProductWith(ctx, req.(*CreateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RentautomationService_CreateCustomerWith_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RentautomationServiceServer).CreateCustomerWith(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RentautomationService/CreateCustomerWith",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RentautomationServiceServer).CreateCustomerWith(ctx, req.(*CreateCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RentautomationService_UpdateCustomerWith_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RentautomationServiceServer).UpdateCustomerWith(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RentautomationService/UpdateCustomerWith",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RentautomationServiceServer).UpdateCustomerWith(ctx, req.(*CustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RentautomationService_UpdateCustomerBalanceWith_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RentautomationServiceServer).UpdateCustomerBalanceWith(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RentautomationService/UpdateCustomerBalanceWith",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RentautomationServiceServer).UpdateCustomerBalanceWith(ctx, req.(*CreateCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RentautomationService_CreateSupplierWith_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSupplierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RentautomationServiceServer).CreateSupplierWith(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RentautomationService/CreateSupplierWith",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RentautomationServiceServer).CreateSupplierWith(ctx, req.(*CreateSupplierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RentautomationService_UpdateSupplierWith_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SupplierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RentautomationServiceServer).UpdateSupplierWith(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RentautomationService/UpdateSupplierWith",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RentautomationServiceServer).UpdateSupplierWith(ctx, req.(*SupplierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RentautomationService_UpdateSupplierBalanceWith_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSupplierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RentautomationServiceServer).UpdateSupplierBalanceWith(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RentautomationService/UpdateSupplierBalanceWith",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RentautomationServiceServer).UpdateSupplierBalanceWith(ctx, req.(*CreateSupplierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RentautomationService_CreateStaffWith_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RentautomationServiceServer).CreateStaffWith(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RentautomationService/CreateStaffWith",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RentautomationServiceServer).CreateStaffWith(ctx, req.(*StaffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RentautomationService_UpdateStaffWith_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RentautomationServiceServer).UpdateStaffWith(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RentautomationService/UpdateStaffWith",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RentautomationServiceServer).UpdateStaffWith(ctx, req.(*StaffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RentautomationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.RentautomationService",
	HandlerType: (*RentautomationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateExample",
			Handler:    _RentautomationService_CreateExample_Handler,
		},
		{
			MethodName: "CreateAccount",
			Handler:    _RentautomationService_CreateAccount_Handler,
		},
		{
			MethodName: "CreateCategory",
			Handler:    _RentautomationService_CreateCategory_Handler,
		},
		{
			MethodName: "CreateCustomer",
			Handler:    _RentautomationService_CreateCustomer_Handler,
		},
		{
			MethodName: "CreateOrder",
			Handler:    _RentautomationService_CreateOrder_Handler,
		},
		{
			MethodName: "CreateOrderDetail",
			Handler:    _RentautomationService_CreateOrderDetail_Handler,
		},
		{
			MethodName: "CreatePayment",
			Handler:    _RentautomationService_CreatePayment_Handler,
		},
		{
			MethodName: "CreateProduct",
			Handler:    _RentautomationService_CreateProduct_Handler,
		},
		{
			MethodName: "CreateStaff",
			Handler:    _RentautomationService_CreateStaff_Handler,
		},
		{
			MethodName: "CreateTransaction",
			Handler:    _RentautomationService_CreateTransaction_Handler,
		},
		{
			MethodName: "CreateProductWith",
			Handler:    _RentautomationService_CreateProductWith_Handler,
		},
		{
			MethodName: "UpdateProductWith",
			Handler:    _RentautomationService_UpdateProductWith_Handler,
		},
		{
			MethodName: "CreateCustomerWith",
			Handler:    _RentautomationService_CreateCustomerWith_Handler,
		},
		{
			MethodName: "UpdateCustomerWith",
			Handler:    _RentautomationService_UpdateCustomerWith_Handler,
		},
		{
			MethodName: "UpdateCustomerBalanceWith",
			Handler:    _RentautomationService_UpdateCustomerBalanceWith_Handler,
		},
		{
			MethodName: "CreateSupplierWith",
			Handler:    _RentautomationService_CreateSupplierWith_Handler,
		},
		{
			MethodName: "UpdateSupplierWith",
			Handler:    _RentautomationService_UpdateSupplierWith_Handler,
		},
		{
			MethodName: "UpdateSupplierBalanceWith",
			Handler:    _RentautomationService_UpdateSupplierBalanceWith_Handler,
		},
		{
			MethodName: "CreateStaffWith",
			Handler:    _RentautomationService_CreateStaffWith_Handler,
		},
		{
			MethodName: "UpdateStaffWith",
			Handler:    _RentautomationService_UpdateStaffWith_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetExamples",
			Handler:       _RentautomationService_GetExamples_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAccounts",
			Handler:       _RentautomationService_GetAccounts_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetCategories",
			Handler:       _RentautomationService_GetCategories_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetCustomers",
			Handler:       _RentautomationService_GetCustomers_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetOrders",
			Handler:       _RentautomationService_GetOrders_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetOrderDetails",
			Handler:       _RentautomationService_GetOrderDetails_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetPayments",
			Handler:       _RentautomationService_GetPayments_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetProducts",
			Handler:       _RentautomationService_GetProducts_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetStaff",
			Handler:       _RentautomationService_GetStaff_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetTransactions",
			Handler:       _RentautomationService_GetTransactions_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "customer.proto",
}

func init() { proto1.RegisterFile("customer.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1749 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xc4, 0x58, 0xcd, 0x6e, 0x1b, 0x47,
	0x12, 0xe6, 0x90, 0xa2, 0x44, 0x16, 0x45, 0xd2, 0xea, 0xb5, 0x04, 0x7a, 0x56, 0xbb, 0x10, 0x1a,
	0x0b, 0x43, 0xbb, 0x30, 0xb4, 0x5a, 0x2d, 0xb0, 0xde, 0x5d, 0xc3, 0x49, 0x64, 0xd9, 0x16, 0x14,
	0xc3, 0xb2, 0x32, 0xb2, 0x11, 0xe4, 0x38, 0x9a, 0x69, 0x4b, 0x03, 0x93, 0x33, 0xf4, 0x4c, 0xd3,
	0x09, 0x73, 0xce, 0x21, 0x40, 0xae, 0x79, 0x84, 0xdc, 0x92, 0x07, 0x48, 0xde, 0x23, 0x97, 0x1c,
	0x73, 0xcb, 0x03, 0xe4, 0x01, 0x82, 0xfe, 0x9b, 0xfe, 0x19, 0x0e, 0x13, 0xc7, 0x06, 0x72, 0x92,
	0xea, 0xab, 0xea, 0x9e, 0xaf, 0xaa, 0xeb, 0xa7, 0x9b, 0x30, 0x88, 0x66, 0x05, 0xcd, 0x26, 0x24,
	0xdf, 0x9b, 0xe6, 0x19, 0xcd, 0x50, 0x9b, 0xff, 0xc1, 0x5f, 0x37, 0x61, 0xf0, 0xe0, 0x93, 0x70,
	0x32, 0x1d, 0x93, 0x80, 0xbc, 0x9c, 0x91, 0x82, 0xa2, 0x01, 0x34, 0x93, 0x78, 0xe4, 0xed, 0x78,
	0xbb, 0x2b, 0x41, 0x33, 0x89, 0x11, 0x82, 0x95, 0x34, 0x9c, 0x90, 0x51, 0x73, 0xc7, 0xdb, 0xed,
	0x06, 0xfc, 0x7f, 0x74, 0x1d, 0xda, 0x64, 0x12, 0x26, 0xe3, 0x51, 0x8b, 0x83, 0x42, 0x60, 0xe8,
	0xf4, 0x2a, 0x4b, 0xc9, 0x68, 0x45, 0xa0, 0x5c, 0x40, 0x77, 0xa0, 0x1b, 0xc6, 0x71, 0x4e, 0x8a,
	0x82, 0x14, 0xa3, 0xf6, 0x4e, 0x6b, 0xb7, 0x77, 0xf0, 0x17, 0x41, 0x62, 0xcf, 0xfe, 0xf2, 0xde,
	0xa1, 0x30, 0x0b, 0xb4, 0xbd, 0xff, 0x85, 0x07, 0x6b, 0x12, 0x46, 0x5b, 0xb0, 0x5a, 0xd0, 0x9c,
	0x10, 0xca, 0xc9, 0x75, 0x03, 0x29, 0x31, 0x82, 0x51, 0x42, 0xe7, 0x8a, 0x20, 0xfb, 0x9f, 0x51,
	0x29, 0x68, 0x48, 0x89, 0x22, 0xc8, 0x05, 0x74, 0x0d, 0x5a, 0x9f, 0x26, 0x53, 0x49, 0x8f, 0xfd,
	0x8b, 0x6e, 0xc1, 0x46, 0x52, 0x9c, 0x5f, 0x25, 0xd3, 0x69, 0x92, 0x5e, 0xca, 0x0f, 0x8d, 0xda,
	0x3b, 0xde, 0x6e, 0x27, 0xa8, 0x2a, 0xf0, 0x1d, 0x18, 0x96, 0x94, 0x8b, 0x69, 0x96, 0x16, 0xa4,
	0x12, 0xad, 0x11, 0xac, 0x15, 0xb3, 0x28, 0x62, 0xdb, 0x34, 0xf9, 0x36, 0x4a, 0xc4, 0x7f, 0x87,
	0xbe, 0x5c, 0xfc, 0x30, 0x19, 0x53, 0x92, 0x33, 0xd3, 0x17, 0x64, 0xfe, 0x71, 0x96, 0xc7, 0xd2,
	0x21, 0x25, 0xe2, 0xcf, 0x3c, 0xb8, 0x7e, 0x94, 0x93, 0x90, 0x92, 0xb3, 0x3c, 0x8b, 0x67, 0x11,
	0x55, 0x67, 0xf3, 0x4f, 0x58, 0x9b, 0x0a, 0x84, 0x2f, 0xe9, 0x1d, 0x6c, 0xca, 0x48, 0xda, 0x76,
	0x81, 0xb2, 0x42, 0x77, 0xa0, 0x97, 0xe5, 0x31, 0xc9, 0xef, 0x13, 0xca, 0x8e, 0xab, 0xc9, 0x17,
	0xdd, 0x90, 0x8b, 0x9e, 0x68, 0x8d, 0x5a, 0x68, 0x5a, 0xe3, 0xef, 0x3c, 0xd8, 0x14, 0x34, 0x8e,
	0x64, 0xf2, 0x28, 0x1e, 0x07, 0xd0, 0x51, 0xf9, 0x24, 0x89, 0x6c, 0xc9, 0x3d, 0x1d, 0xcb, 0xa0,
	0xb4, 0x63, 0x54, 0x68, 0x1e, 0xa6, 0x45, 0x18, 0xd1, 0x24, 0x4b, 0x1d, 0x2a, 0x4f, 0xb5, 0xa6,
	0xa4, 0x62, 0x58, 0x33, 0xc7, 0xc3, 0x28, 0xca, 0x66, 0x29, 0xe5, 0x27, 0xaa, 0x1d, 0x3f, 0x14,
	0x68, 0xe9, 0xb8, 0xb4, 0x32, 0xb8, 0x9f, 0xcf, 0xa6, 0xd3, 0x71, 0xf2, 0x5b, 0xb8, 0x3b, 0x96,
	0x7f, 0x18, 0xf7, 0x2f, 0x9b, 0xb0, 0x7e, 0x4e, 0xc3, 0xe7, 0xcf, 0x15, 0x65, 0x96, 0x54, 0x4c,
	0x3e, 0x51, 0x99, 0xa6, 0x44, 0x56, 0x13, 0x79, 0x36, 0x26, 0x27, 0x31, 0xe7, 0xb4, 0x12, 0x48,
	0x09, 0xdd, 0x84, 0x81, 0x30, 0x99, 0x84, 0x97, 0xe4, 0x2c, 0xa4, 0x57, 0xb2, 0x10, 0x1c, 0x14,
	0x6d, 0x43, 0xf7, 0x79, 0x92, 0x17, 0xf4, 0x94, 0x55, 0xb8, 0xa8, 0x0b, 0x0d, 0xa0, 0xbf, 0x02,
	0x14, 0x24, 0xca, 0xd2, 0x98, 0xab, 0xdb, 0x5c, 0x6d, 0x20, 0xba, 0x0d, 0xac, 0x9a, 0x6d, 0xc0,
	0x87, 0xce, 0x34, 0x2c, 0x0a, 0x9e, 0xd8, 0x6b, 0x5c, 0x51, 0xca, 0x68, 0x07, 0x7a, 0xbc, 0x2b,
	0x9c, 0xce, 0x26, 0x17, 0x24, 0x1f, 0x75, 0xb8, 0xda, 0x84, 0x98, 0xaf, 0xb2, 0xfc, 0x47, 0x5d,
	0x51, 0x15, 0x52, 0xc4, 0xff, 0x82, 0x1e, 0x8f, 0x8a, 0x2c, 0x1f, 0x0c, 0xeb, 0xdc, 0x99, 0x47,
	0x56, 0x0d, 0x59, 0x18, 0x3e, 0x84, 0x5e, 0x90, 0xe9, 0xd6, 0xa6, 0xa3, 0xe5, 0x59, 0xd1, 0xf2,
	0xa1, 0xc3, 0xfe, 0x3b, 0xd5, 0x6d, 0xae, 0x94, 0xf1, 0xcf, 0x4d, 0x18, 0x38, 0x55, 0xb8, 0x0d,
	0x5d, 0x59, 0x5f, 0xe5, 0x4e, 0x1a, 0x40, 0xff, 0x80, 0x6b, 0x4a, 0x28, 0x83, 0x2f, 0x36, 0xad,
	0xe0, 0x3c, 0x1c, 0x02, 0xe3, 0xdf, 0x6e, 0xc9, 0x70, 0x68, 0x88, 0x1f, 0x81, 0x4c, 0xcb, 0x93,
	0x98, 0x9f, 0xd0, 0x4a, 0x60, 0x20, 0x4c, 0x1f, 0x85, 0x94, 0x5c, 0x66, 0xf9, 0xfc, 0x24, 0xe6,
	0x47, 0xb4, 0x12, 0x18, 0x08, 0x0b, 0xe7, 0x45, 0x98, 0x47, 0x59, 0x4c, 0xe4, 0x21, 0x29, 0x11,
	0xed, 0xc2, 0xf0, 0xe5, 0x2c, 0x4c, 0x69, 0x42, 0xe7, 0x67, 0x24, 0x7f, 0x96, 0x26, 0x54, 0x9e,
	0x96, 0x0b, 0xa3, 0xbf, 0x41, 0xbf, 0x08, 0xc7, 0x84, 0xfd, 0x7f, 0x96, 0x27, 0x11, 0xe1, 0xc7,
	0xe6, 0x05, 0x36, 0xc8, 0xf6, 0x4b, 0xd2, 0x28, 0x9b, 0x18, 0x76, 0x5d, 0x6e, 0xe7, 0xc2, 0xec,
	0xe4, 0x66, 0x69, 0x42, 0x8b, 0x93, 0xf4, 0x9c, 0x66, 0xd1, 0x8b, 0x11, 0x70, 0x33, 0x0b, 0xc3,
	0xb7, 0xa1, 0x2f, 0xa3, 0x2e, 0x8f, 0xfb, 0x26, 0x0c, 0x64, 0x5c, 0xec, 0x03, 0x77, 0x50, 0xfc,
	0x0c, 0x86, 0x47, 0xd2, 0x7d, 0x75, 0x5e, 0x76, 0x8c, 0xbc, 0x4a, 0x8c, 0x30, 0xac, 0x2b, 0xc9,
	0x48, 0x01, 0x0b, 0xc3, 0xff, 0x87, 0x81, 0xda, 0x56, 0x12, 0xda, 0x85, 0xa1, 0xb2, 0xb0, 0x19,
	0xb9, 0x30, 0xfe, 0xc1, 0x83, 0xa1, 0xdb, 0x41, 0x19, 0x27, 0x09, 0x19, 0x9c, 0x4a, 0x84, 0x0d,
	0xa6, 0x52, 0x72, 0xd2, 0xa8, 0xaa, 0xb0, 0xcb, 0xb8, 0xb5, 0xbc, 0x8c, 0x57, 0x2a, 0x65, 0xec,
	0x14, 0x65, 0x7b, 0x69, 0x51, 0xae, 0xda, 0x45, 0xc9, 0xe2, 0x22, 0xe9, 0x18, 0x71, 0x91, 0x88,
	0x1b, 0x17, 0x1b, 0xc6, 0x3f, 0x7a, 0x30, 0x74, 0xbb, 0xb3, 0x9d, 0xef, 0x5e, 0x25, 0xdf, 0x6f,
	0xc1, 0x46, 0x29, 0xb9, 0x71, 0xa9, 0x28, 0x98, 0x67, 0x51, 0x36, 0x99, 0x86, 0xe9, 0xdc, 0xac,
	0x2f, 0x03, 0xe2, 0x67, 0x9f, 0xa5, 0x34, 0x8c, 0xe8, 0xc3, 0x54, 0x47, 0xc7, 0xc2, 0xde, 0x34,
	0x3e, 0xca, 0x45, 0x1d, 0x1f, 0x45, 0xd4, 0x89, 0x8f, 0x03, 0xe3, 0xcf, 0x3d, 0x18, 0xd8, 0x33,
	0x82, 0x1d, 0xb4, 0x9c, 0x12, 0xba, 0xf5, 0x94, 0x80, 0x93, 0x54, 0xcd, 0x4a, 0x52, 0xd9, 0xc1,
	0x6d, 0x55, 0x82, 0xcb, 0x9b, 0xc5, 0x38, 0x4c, 0x23, 0x11, 0x07, 0x2f, 0x50, 0x22, 0x2b, 0x47,
	0xc9, 0x44, 0x97, 0xa3, 0xfc, 0xae, 0x53, 0x8e, 0x36, 0x8a, 0xbf, 0x6d, 0xc1, 0x3a, 0xbf, 0x67,
	0x18, 0xb3, 0x8c, 0xdf, 0x31, 0xf4, 0x2c, 0x93, 0x22, 0x6b, 0x33, 0xe2, 0xf6, 0x91, 0x45, 0xb3,
	0x09, 0x49, 0x29, 0x77, 0xa0, 0x1f, 0xd8, 0x20, 0x4b, 0x80, 0x49, 0x96, 0x92, 0xf9, 0xe3, 0xec,
	0x15, 0x61, 0xc0, 0xd3, 0xf9, 0x54, 0x1c, 0x6c, 0x3f, 0xa8, 0x2a, 0x58, 0xbc, 0x2e, 0x92, 0xf1,
	0x38, 0x49, 0x2f, 0x4f, 0x33, 0x35, 0xdf, 0x4a, 0xc0, 0x9c, 0xab, 0x6d, 0x7b, 0xae, 0xda, 0x91,
	0x5c, 0xfd, 0x95, 0x48, 0xae, 0x55, 0x22, 0xb9, 0x0d, 0x5d, 0x41, 0x9b, 0xdd, 0x41, 0x3b, 0xe2,
	0x9c, 0x4a, 0x80, 0x0f, 0x90, 0x70, 0xce, 0x48, 0x9e, 0xc4, 0xbc, 0x49, 0xb2, 0x01, 0xa2, 0x00,
	0x36, 0x8d, 0x48, 0x9e, 0x67, 0xf9, 0xe3, 0xe2, 0x92, 0xb7, 0xc6, 0x6e, 0x50, 0xca, 0x8c, 0x71,
	0x94, 0x4d, 0x78, 0x74, 0x7a, 0x22, 0xd1, 0xa4, 0xc8, 0xf6, 0x4c, 0x8a, 0xfb, 0x64, 0x4c, 0x28,
	0x89, 0x47, 0xeb, 0x3c, 0x1e, 0x1a, 0x60, 0x93, 0x2f, 0x29, 0xce, 0xc2, 0x24, 0x1e, 0xf5, 0xb9,
	0x4a, 0x4a, 0xec, 0x5b, 0x49, 0xf1, 0x20, 0x4e, 0xd8, 0xa2, 0x01, 0xd7, 0x94, 0x32, 0x9b, 0xb7,
	0xfc, 0xe4, 0xf4, 0xbc, 0xe5, 0x1e, 0x38, 0xf3, 0xd6, 0xc4, 0xf0, 0x37, 0x1e, 0x0c, 0xce, 0x84,
	0x23, 0xe6, 0xb0, 0x2c, 0x7d, 0xf5, 0x5c, 0x5f, 0x77, 0x61, 0x48, 0x33, 0x1a, 0x8e, 0xf9, 0x87,
	0xc4, 0xd0, 0x68, 0x8a, 0xa1, 0xe1, 0xc0, 0x8c, 0x69, 0x9c, 0x14, 0xfa, 0x1a, 0xe5, 0x05, 0xa5,
	0x8c, 0xfe, 0x03, 0x5b, 0xdc, 0x9c, 0x5b, 0x7e, 0x98, 0xd0, 0xab, 0xfb, 0xca, 0x52, 0xa4, 0x71,
	0x8d, 0x96, 0x0f, 0x19, 0x41, 0xc5, 0x18, 0x32, 0x02, 0x70, 0x87, 0x8c, 0x85, 0xe2, 0x9f, 0x3c,
	0x40, 0xd5, 0xdb, 0xb3, 0xce, 0x60, 0x8e, 0x96, 0xfe, 0xda, 0xa0, 0x59, 0x01, 0x4d, 0xbb, 0x02,
	0xac, 0x8b, 0x45, 0xcb, 0xbd, 0x58, 0x2c, 0xcf, 0x65, 0xf6, 0xf8, 0xe2, 0xf1, 0x6b, 0x73, 0x97,
	0x85, 0x50, 0x32, 0xfa, 0x40, 0x8e, 0x74, 0x9e, 0xca, 0x5e, 0x60, 0x83, 0x56, 0x6c, 0x59, 0x2e,
	0xb7, 0x75, 0x6c, 0xf1, 0x11, 0x6c, 0x18, 0x9e, 0xca, 0x38, 0xed, 0x01, 0x32, 0x7c, 0xb2, 0x63,
	0xb5, 0x40, 0x83, 0xbf, 0x6a, 0x02, 0xaa, 0x5e, 0x93, 0x19, 0x3b, 0xe3, 0xa2, 0xac, 0xe3, 0x65,
	0x81, 0x3c, 0x47, 0x34, 0xc0, 0x2b, 0x4a, 0xc4, 0xcd, 0x85, 0x1d, 0x4b, 0xa3, 0x33, 0xb8, 0x30,
	0x6b, 0xe9, 0xbc, 0x59, 0x1c, 0x4e, 0x8c, 0x34, 0x31, 0x21, 0xf3, 0x94, 0xda, 0xf6, 0x29, 0xbd,
	0x69, 0x6f, 0x30, 0xba, 0x4e, 0xc7, 0xea, 0x3a, 0x2c, 0xd6, 0x46, 0x94, 0x74, 0xac, 0x0d, 0xf6,
	0x4e, 0xac, 0xab, 0x9a, 0x83, 0xef, 0xaf, 0xc1, 0x66, 0x40, 0x52, 0x1a, 0xce, 0x68, 0x36, 0x09,
	0x99, 0xe6, 0x9c, 0xe4, 0xaf, 0x58, 0x32, 0xbc, 0x03, 0xbd, 0x63, 0x42, 0xe5, 0x23, 0xb4, 0x40,
	0xd7, 0xed, 0x57, 0xb8, 0xf8, 0x9c, 0xbf, 0xb9, 0xf0, 0x6d, 0x8e, 0x1b, 0xfb, 0x1e, 0x7a, 0x0f,
	0xfa, 0xe2, 0x49, 0x25, 0x75, 0x68, 0xb1, 0xad, 0xbf, 0xe5, 0xc2, 0xe2, 0xad, 0x8c, 0x1b, 0xe8,
	0x5d, 0xb5, 0x83, 0x1c, 0x26, 0x68, 0xf1, 0x53, 0xc8, 0x5f, 0x0c, 0xe3, 0x86, 0x74, 0x41, 0xc2,
	0xda, 0x05, 0x6b, 0x36, 0xd5, 0xae, 0xde, 0xf7, 0xd0, 0x3d, 0x18, 0xc8, 0x17, 0xad, 0xbc, 0xa3,
	0xa1, 0xf2, 0xe1, 0x6a, 0x5f, 0x1a, 0xfd, 0x1a, 0x1c, 0x37, 0xd0, 0x3d, 0xe8, 0x1f, 0x13, 0x2a,
	0xf1, 0x84, 0x14, 0xa5, 0x13, 0xf6, 0x05, 0xb1, 0x7e, 0x07, 0x8b, 0x87, 0x7a, 0x62, 0xd6, 0x3c,
	0xa0, 0xfd, 0x1a, 0x1c, 0x37, 0xd0, 0x21, 0xac, 0x33, 0x1e, 0x12, 0x37, 0x68, 0x58, 0xf7, 0xb1,
	0xfa, 0x0d, 0xf6, 0x3d, 0xf4, 0x3f, 0xe8, 0x09, 0x1a, 0xbc, 0xc4, 0xd1, 0x9f, 0xcc, 0x1f, 0x06,
	0x14, 0x81, 0x45, 0x20, 0x6e, 0xa0, 0xff, 0x42, 0xf7, 0x98, 0x50, 0x0e, 0x16, 0x08, 0x99, 0x36,
	0xf2, 0xbb, 0x8b, 0xd7, 0xed, 0x7b, 0xe8, 0x11, 0x6c, 0x18, 0x1f, 0x15, 0x8d, 0x02, 0xd5, 0xff,
	0x26, 0xe1, 0xd7, 0xab, 0x70, 0x03, 0xbd, 0x0f, 0x43, 0x45, 0x43, 0xa8, 0x0a, 0x34, 0xaa, 0xda,
	0x4b, 0x4a, 0xcb, 0x76, 0xda, 0xf7, 0x74, 0x76, 0xca, 0xa1, 0x50, 0x46, 0xd4, 0x1e, 0x69, 0xfe,
	0x62, 0xb8, 0xcc, 0x4e, 0x09, 0xeb, 0xec, 0xb4, 0x66, 0x4c, 0xed, 0x6a, 0x8b, 0x80, 0xfc, 0xf9,
	0x66, 0xf1, 0xcf, 0x3b, 0xfe, 0x62, 0x58, 0x13, 0x10, 0xb0, 0x41, 0xc0, 0x7c, 0x49, 0xd5, 0xae,
	0x36, 0xf3, 0x81, 0x3f, 0xb4, 0xcb, 0x7c, 0x30, 0x7f, 0x8c, 0xf0, 0x17, 0x81, 0xb8, 0x81, 0x6e,
	0x43, 0xe7, 0x98, 0x50, 0xb1, 0x0e, 0x99, 0x26, 0x4e, 0x3a, 0xd8, 0xcb, 0xcc, 0x74, 0x30, 0x5a,
	0x1f, 0xaa, 0xff, 0x6d, 0xc5, 0xaf, 0x57, 0x95, 0xe9, 0x60, 0xa8, 0x74, 0x3a, 0x54, 0x3a, 0xeb,
	0xd2, 0x9d, 0xf6, 0x3d, 0xf4, 0x44, 0x11, 0x93, 0x81, 0x62, 0x57, 0x07, 0xf4, 0x67, 0x55, 0x4d,
	0x0b, 0x7e, 0x9e, 0xf3, 0x97, 0x29, 0x71, 0x83, 0x6d, 0xf8, 0x6c, 0x1a, 0xbf, 0xc5, 0x0d, 0x03,
	0x40, 0x76, 0x17, 0xe1, 0x3b, 0x6e, 0x5b, 0x8b, 0xdc, 0x7e, 0xb2, 0x54, 0x8b, 0x1b, 0xe8, 0x21,
	0x20, 0x41, 0xd2, 0xda, 0xf3, 0xf5, 0xbb, 0xd3, 0x47, 0x70, 0xc3, 0xde, 0xe7, 0x9e, 0x78, 0x4a,
	0xbc, 0x05, 0x8a, 0xa5, 0xdb, 0xea, 0x65, 0xb5, 0x60, 0x4f, 0xe7, 0x5d, 0xe9, 0x2f, 0xd5, 0x9a,
	0x6e, 0x5b, 0x7b, 0xd6, 0xfc, 0x32, 0xe8, 0xd7, 0xe0, 0xa6, 0xdb, 0x4a, 0x55, 0xef, 0xf6, 0xeb,
	0x52, 0xbc, 0x0b, 0x43, 0xa3, 0x38, 0xf9, 0x86, 0xaf, 0x53, 0xa0, 0x77, 0x61, 0x28, 0x99, 0xfd,
	0x9e, 0xe5, 0x17, 0xab, 0x1c, 0xfd, 0xf7, 0x2f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xfc, 0xa2, 0xd5,
	0x47, 0x49, 0x18, 0x00, 0x00,
}
