// Code generated by protoc-gen-go.
// source: customer.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	customer.proto

It has these top-level messages:
	CustomerRequest
	CustomerResponse
	CustomerFilter
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

// Request message for creating a new customer
type CustomerRequest struct {
	Id        uint64                     `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name      string                     `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Email     string                     `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Phone     string                     `protobuf:"bytes,4,opt,name=phone" json:"phone,omitempty"`
	Addresses []*CustomerRequest_Address `protobuf:"bytes,5,rep,name=addresses" json:"addresses,omitempty"`
}

func (m *CustomerRequest) Reset()                    { *m = CustomerRequest{} }
func (m *CustomerRequest) String() string            { return proto1.CompactTextString(m) }
func (*CustomerRequest) ProtoMessage()               {}
func (*CustomerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CustomerRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CustomerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CustomerRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CustomerRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *CustomerRequest) GetAddresses() []*CustomerRequest_Address {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type CustomerRequest_Address struct {
	Street            string `protobuf:"bytes,1,opt,name=street" json:"street,omitempty"`
	City              string `protobuf:"bytes,2,opt,name=city" json:"city,omitempty"`
	State             string `protobuf:"bytes,3,opt,name=state" json:"state,omitempty"`
	Zip               string `protobuf:"bytes,4,opt,name=zip" json:"zip,omitempty"`
	IsShippingAddress bool   `protobuf:"varint,5,opt,name=isShippingAddress" json:"isShippingAddress,omitempty"`
}

func (m *CustomerRequest_Address) Reset()                    { *m = CustomerRequest_Address{} }
func (m *CustomerRequest_Address) String() string            { return proto1.CompactTextString(m) }
func (*CustomerRequest_Address) ProtoMessage()               {}
func (*CustomerRequest_Address) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *CustomerRequest_Address) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

func (m *CustomerRequest_Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *CustomerRequest_Address) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *CustomerRequest_Address) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

func (m *CustomerRequest_Address) GetIsShippingAddress() bool {
	if m != nil {
		return m.IsShippingAddress
	}
	return false
}

type CustomerResponse struct {
	Id      uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Success bool   `protobuf:"varint,2,opt,name=success" json:"success,omitempty"`
}

func (m *CustomerResponse) Reset()                    { *m = CustomerResponse{} }
func (m *CustomerResponse) String() string            { return proto1.CompactTextString(m) }
func (*CustomerResponse) ProtoMessage()               {}
func (*CustomerResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CustomerResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CustomerResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type CustomerFilter struct {
	Keyword string `protobuf:"bytes,1,opt,name=keyword" json:"keyword,omitempty"`
}

func (m *CustomerFilter) Reset()                    { *m = CustomerFilter{} }
func (m *CustomerFilter) String() string            { return proto1.CompactTextString(m) }
func (*CustomerFilter) ProtoMessage()               {}
func (*CustomerFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CustomerFilter) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func init() {
	proto1.RegisterType((*CustomerRequest)(nil), "proto.CustomerRequest")
	proto1.RegisterType((*CustomerRequest_Address)(nil), "proto.CustomerRequest.Address")
	proto1.RegisterType((*CustomerResponse)(nil), "proto.CustomerResponse")
	proto1.RegisterType((*CustomerFilter)(nil), "proto.CustomerFilter")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CustomerService service

type CustomerServiceClient interface {
	// Get all Customers with filter - A server-to-client streaming RPC.
	GetCustomers(ctx context.Context, in *CustomerFilter, opts ...grpc.CallOption) (CustomerService_GetCustomersClient, error)
	// Create a new Customer - A simple RPC
	CreateCustomer(ctx context.Context, in *CustomerRequest, opts ...grpc.CallOption) (*CustomerResponse, error)
}

type customerServiceClient struct {
	cc *grpc.ClientConn
}

func NewCustomerServiceClient(cc *grpc.ClientConn) CustomerServiceClient {
	return &customerServiceClient{cc}
}

func (c *customerServiceClient) GetCustomers(ctx context.Context, in *CustomerFilter, opts ...grpc.CallOption) (CustomerService_GetCustomersClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_CustomerService_serviceDesc.Streams[0], c.cc, "/proto.CustomerService/GetCustomers", opts...)
	if err != nil {
		return nil, err
	}
	x := &customerServiceGetCustomersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CustomerService_GetCustomersClient interface {
	Recv() (*CustomerRequest, error)
	grpc.ClientStream
}

type customerServiceGetCustomersClient struct {
	grpc.ClientStream
}

func (x *customerServiceGetCustomersClient) Recv() (*CustomerRequest, error) {
	m := new(CustomerRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *customerServiceClient) CreateCustomer(ctx context.Context, in *CustomerRequest, opts ...grpc.CallOption) (*CustomerResponse, error) {
	out := new(CustomerResponse)
	err := grpc.Invoke(ctx, "/proto.CustomerService/CreateCustomer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CustomerService service

type CustomerServiceServer interface {
	// Get all Customers with filter - A server-to-client streaming RPC.
	GetCustomers(*CustomerFilter, CustomerService_GetCustomersServer) error
	// Create a new Customer - A simple RPC
	CreateCustomer(context.Context, *CustomerRequest) (*CustomerResponse, error)
}

func RegisterCustomerServiceServer(s *grpc.Server, srv CustomerServiceServer) {
	s.RegisterService(&_CustomerService_serviceDesc, srv)
}

func _CustomerService_GetCustomers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CustomerFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CustomerServiceServer).GetCustomers(m, &customerServiceGetCustomersServer{stream})
}

type CustomerService_GetCustomersServer interface {
	Send(*CustomerRequest) error
	grpc.ServerStream
}

type customerServiceGetCustomersServer struct {
	grpc.ServerStream
}

func (x *customerServiceGetCustomersServer) Send(m *CustomerRequest) error {
	return x.ServerStream.SendMsg(m)
}

func _CustomerService_CreateCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).CreateCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CustomerService/CreateCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).CreateCustomer(ctx, req.(*CustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CustomerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CustomerService",
	HandlerType: (*CustomerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCustomer",
			Handler:    _CustomerService_CreateCustomer_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetCustomers",
			Handler:       _CustomerService_GetCustomers_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "customer.proto",
}

func init() { proto1.RegisterFile("customer.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x91, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0x86, 0xd9, 0x42, 0x41, 0x46, 0x53, 0x71, 0xa2, 0xb8, 0xe1, 0x60, 0x9a, 0x9e, 0x1a, 0x63,
	0x88, 0xc1, 0x2b, 0x17, 0x42, 0xa2, 0xf7, 0xf2, 0x04, 0xb5, 0x9d, 0xc8, 0x46, 0x68, 0xeb, 0xee,
	0xa2, 0xc1, 0x57, 0xf0, 0x09, 0x7c, 0x08, 0xdf, 0xd1, 0xec, 0xb6, 0x1b, 0x12, 0xaa, 0xa7, 0xce,
	0xff, 0xff, 0xb3, 0xb3, 0xdf, 0x4e, 0x21, 0xc8, 0x76, 0x4a, 0x97, 0x5b, 0x92, 0xd3, 0x4a, 0x96,
	0xba, 0x44, 0xdf, 0x7e, 0xa2, 0x1f, 0x0f, 0xce, 0x97, 0x4d, 0x92, 0xd0, 0xdb, 0x8e, 0x94, 0xc6,
	0x00, 0x3c, 0x91, 0x73, 0x16, 0xb2, 0xb8, 0x97, 0x78, 0x22, 0x47, 0x84, 0x5e, 0x91, 0x6e, 0x89,
	0x7b, 0x21, 0x8b, 0x87, 0x89, 0xad, 0xf1, 0x12, 0x7c, 0xda, 0xa6, 0x62, 0xc3, 0xbb, 0xd6, 0xac,
	0x85, 0x71, 0xab, 0x75, 0x59, 0x10, 0xef, 0xd5, 0xae, 0x15, 0x38, 0x87, 0x61, 0x9a, 0xe7, 0x92,
	0x94, 0x22, 0xc5, 0xfd, 0xb0, 0x1b, 0x9f, 0xce, 0x6e, 0x6a, 0x8a, 0xe9, 0xd1, 0xd5, 0xd3, 0x45,
	0xdd, 0x97, 0x1c, 0x0e, 0x4c, 0xbe, 0x18, 0x0c, 0x1a, 0x1b, 0xc7, 0xd0, 0x57, 0x5a, 0x12, 0x69,
	0x4b, 0x37, 0x4c, 0x1a, 0x65, 0x08, 0x33, 0xa1, 0xf7, 0x8e, 0xd0, 0xd4, 0x86, 0x45, 0xe9, 0x54,
	0x93, 0x23, 0xb4, 0x02, 0x47, 0xd0, 0xfd, 0x14, 0x55, 0xc3, 0x67, 0x4a, 0xbc, 0x83, 0x0b, 0xa1,
	0x56, 0x6b, 0x51, 0x55, 0xa2, 0x78, 0x69, 0x2e, 0xe2, 0x7e, 0xc8, 0xe2, 0x93, 0xa4, 0x1d, 0x44,
	0x73, 0x18, 0x1d, 0x98, 0x55, 0x55, 0x16, 0x8a, 0x5a, 0xfb, 0xe2, 0x30, 0x50, 0xbb, 0x2c, 0x33,
	0x73, 0x3c, 0x3b, 0xc7, 0xc9, 0xe8, 0x16, 0x02, 0x77, 0xfa, 0x51, 0x6c, 0x34, 0x49, 0xd3, 0xfb,
	0x4a, 0xfb, 0x8f, 0x52, 0xe6, 0xcd, 0x93, 0x9c, 0x9c, 0x7d, 0xb3, 0xc3, 0x9f, 0x59, 0x91, 0x7c,
	0x17, 0x19, 0xe1, 0x02, 0xce, 0x9e, 0x48, 0x3b, 0x57, 0xe1, 0xd5, 0xd1, 0x1a, 0xeb, 0xa1, 0x93,
	0xf1, 0xdf, 0xdb, 0x8d, 0x3a, 0xf7, 0x0c, 0x97, 0x10, 0x2c, 0x25, 0xa5, 0x9a, 0x5c, 0x88, 0xff,
	0x74, 0x4f, 0xae, 0x5b, 0x7e, 0xfd, 0xde, 0xa8, 0xf3, 0xdc, 0xb7, 0xc9, 0xc3, 0x6f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xda, 0xc3, 0x92, 0x4e, 0x55, 0x02, 0x00, 0x00,
}
